# general settings
name: RFEPFusion_LLIE_vi_NTIRE2024_pretrained
model_type: LLIEModel_VI
scale: 1
num_gpu: 4  
manual_seed: 666
# the size of the input image must be a multiple of 16
# Padding in case images are not multiples of 16
# pad_size: 16  

use_amp: true

# dataset and data loader settings
datasets:
  train:
    name: LLIE_vi_NTIRE2024_TrainSet
    type: PairedImageDataset
    dataroot_lq: /home/hongyuchen/master_thesis/Retinexformer-master/data/NTIRE/train/input
    dataroot_gt: /home/hongyuchen/master_thesis/Retinexformer-master/data/NTIRE/train/target
    io_backend:
      type: disk

    # IMAGENET_INCEPTION_MEAN: mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

    gt_size: [640, 480]
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    # dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: LLIE_vi_NTIRE2024_ValSet
    type: PairedImageDataset
    dataroot_lq: /home/hongyuchen/master_thesis/Retinexformer-master/data/NTIRE/mini_val/input
    dataroot_gt: /home/hongyuchen/master_thesis/Retinexformer-master/data/NTIRE/mini_val/target    
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    io_backend:
      type: disk


# network structures
network_g:
  type: LLIE_VI

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  # ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4  # 初始学习率，实际上不会被用到
    weight_decay: 0
    betas: [0.9, 0.99]

  use_grad_clip: true
  max_grad_norm: 0.1
    
  # mixing_augs:
  #   mixup: true
  #   mixup_beta: 1.2
  #   use_identity: true

  total_iter: 60000  
  # total_epoch: 500
  warmup_iter: -1  # no warm up
  scheduler:
    type: OneCycleLR
    max_lr: !!float 1e-3
    total_steps: 60000  # 保持和total_iter一致 
    pct_start: 0.2
    div_factor: 10
    final_div_factor: 1000
    # last_epoch: -1  # 这个参数在base_model里的resume_training自动会设置好

  # losses
  pixel_opt:
    # type: CharbonnierLoss
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  color_loss:
    type: ColorLoss
    loss_weight: 0.4
    reduction: mean
  

# validation settings
val:
  val_freq: !!float 500
  save_img: false

  # pbar: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      # better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      # better: higher
    # niqe:
    #   type: cal_NIQE

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 500
  save_checkpoint_max_num: 10
  use_tb_logger: true
  wandb:  # 不使用wandb
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
