# general settings
name: RFEPFusion_LLIE_vi_LOL_pretrained
model_type: LLIEModel_VI
scale: 1
num_gpu: 5
manual_seed: 666
# the size of the input image must be a multiple of 16
# Padding in case images are not multiples of 16
# pad_size: 16  
# auto_resume: true

# use_amp: true
use_amp: false

# dataset and data loader settings
datasets:
  train:
    name: LLIE_vi_LOL_TrainSet
    type: PairedImageDataset
    dataroot_lq: /home/hongyuchen/master_thesis/LOLdataset/train/low
    dataroot_gt: /home/hongyuchen/master_thesis/LOLdataset/train/high
    io_backend:
      type: disk
    # 使用 ImageNet 参数进行归一化可能会导致低光图像的特征被压缩或扭曲，从而影响增强效果。底层视觉任务还是不要用ImageNet归一化了
    # IMAGENET_INCEPTION_MEAN: mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
    # mean: [0.485, 0.456, 0.406]
    # std: [0.229, 0.224, 0.225]

    # gt_size: [600, 400]  # [weight, height]
    gt_size: 360
    use_hflip: true
    use_rot: true
    # use_rot: false  # if weight != height, then use_rot must be false

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    # batch_size_per_gpu: 2
    # dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: LLIE_vi_LOL_ValSet
    type: PairedImageDataset
    dataroot_lq: /home/hongyuchen/master_thesis/LOLdataset/test/low
    dataroot_gt: /home/hongyuchen/master_thesis/LOLdataset/test/high    
    # mean: [0.485, 0.456, 0.406]
    # std: [0.229, 0.224, 0.225]
    # gt_size: [640, 480] # useless in val phase
    io_backend:
      type: disk


# network structures
network_g:
  type: LLIE_VI

# path
path:
  pretrain_network_g: /home/hongyuchen/master_thesis/RFEPFusion/experiments/RFEPFusion_LLIE_vi_LOL_pretrained_archived_20250225_124554/best_psnr_12000_psnr_22.577_ssim_0.823.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  # ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4 
    weight_decay: 0.0001
    betas: [0.9, 0.99]

  use_grad_clip: true
  max_grad_norm: 0.01
    
  # mixing_augs:
  #   mixup: true
  #   mixup_beta: 1.2
  #   use_identity: true

  total_iter: 90000  
  # total_epoch: 500
  warmup_iter: -1  # no warm up
  scheduler:
    type: OneCycleLR
    max_lr: !!float 4e-4
    total_steps: 90000  # 保持和total_iter一致 
    pct_start: 0.2
    div_factor: 10
    final_div_factor: 400
    # last_epoch: -1  # 这个参数在base_model里的resume_training自动会设置好

  # losses
  pixel_opt:
    # type: CharbonnierLoss
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # color_loss:
  #   type: ColorLoss
  #   loss_weight: 0.4
  #   reduction: mean
  

# validation settings
val:
  val_freq: !!float 500
  save_img: false

  # pbar: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      # better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      # better: higher
    # niqe:
    #   type: cal_NIQE

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 500  # 每次验证时保存模型
  save_checkpoint_max_num: 10
  use_tb_logger: true
  wandb:  # 不使用wandb
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

# find_unused_parameters: true
